# NumPy Arrays

In [2]:
import numpy as np

## **Q1- Create one dimensional array using python list**
- Data type needs to be float64 
- Print dtype, shape, size, dimension, and memory consumption of each element and total array

In [44]:
#create
a = np.array([1.0,2.0,3.0,4.0,5.0])

In [45]:
# print
print('Data type = ', a.dtype)
print('Shape =', a.shape)
print('Size =', a.size)
print('Dimension =', a.ndim)
print('Each element memory size =', a.itemsize)
print('Total array memory size =', a.nbytes)

Data type =  float64
Shape = (5,)
Size = 5
Dimension = 1
Each element memory size = 8
Total array memory size = 40


## **Q2- Create two dimensional array using python list**
- Print dtype, shape, size, dimension, and memory consumption of each element and total array

In [46]:
#create
b = np.array([[1000000000, 2000000000, 3000000000, 4000000000],
             [5000000000, 6000000000, 7000000000, 8000000000]])

In [47]:
#print
print('Data type = ', b.dtype)
print('Shape =', b.shape)
print('Size =', b.size)
print('Dimension =', b.ndim)
print('Each element memory size =', b.itemsize)
print('Total array memory size =', b.nbytes)

Data type =  int64
Shape = (2, 4)
Size = 8
Dimension = 2
Each element memory size = 8
Total array memory size = 64


## **Q3- Create a length of 10 integer array filled with zeros**

In [9]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## **Q4- Create a 4X5 floating point array filled with 1s**

In [10]:
np.ones((4, 5), dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## **Q5- Create a 3x3 identity matrix**
- Data type: int

In [12]:
np.identity(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## **Q6- Create a one dimensional array of length 10**
- Use numpy function arange to create the array
- Assign new value (12) at the index of 5,6,7

In [14]:
#create
c = np.arange(0, 10)

In [15]:
#asign
c[5:8] = [12, 12, 12]
c

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

## **Q7- Create a 3x3 array**
- a. Use numpy function arange and reshape() to create the array
- b. Select the first two rows of array
- c. Select the second row but only the first two columns 
- d. Select the third column but only the first two rows
- e. Select the first column only
- f. Assign the new value 15 to the last element of third row and third column and print the array

In [18]:
# a.
arr3 = np.arange(1, 10).reshape(3, 3)
# code

In [19]:
#print
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
# b.
arr3[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
# c.
arr3[1, 0:2]

array([4, 5])

In [23]:
# d.
arr3[0:2, 2]

array([3, 6])

In [48]:
# e.
arr3[:, 0].reshape(3, 1)

array([[1],
       [4],
       [7]])

In [30]:
# f.
arr3[-1, -1] = 15

In [31]:
arr3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 15]])

## **Q8- Create two arrays of 3x1 and 3x3 shape**
- Join both the arrays horizontally and store the result in variable concat
- Split the concat array into 2x3 and 1x3 shape

In [34]:
#code
x = np.array([97, 98, 99]).reshape(3, 1)

array([[97],
       [98],
       [99]])

In [92]:
#print
x

array([[97],
       [98],
       [99]])

In [49]:
#code
y = np.arange(1, 10).reshape(3, 3)

In [50]:
#print
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
#code
concat = np.concatenate([x, y], axis = 1)

In [52]:
#print
concat

array([[97,  1,  2,  3],
       [98,  4,  5,  6],
       [99,  7,  8,  9]])

In [53]:
upper, lower = np.vsplit(concat, [2])
[upper, lower]

[array([[97,  1,  2,  3],
        [98,  4,  5,  6]]),
 array([[99,  7,  8,  9]])]

In [54]:
upper, lower = np.hsplit(concat, [2])
[upper, lower]

[array([[97,  1],
        [98,  4],
        [99,  7]]),
 array([[2, 3],
        [5, 6],
        [8, 9]])]

In [43]:
upper, lower = np.hsplit(concat, [3])
[upper, lower]

[array([[97,  1,  2],
        [98,  4,  5],
        [99,  7,  8]]),
 array([[3],
        [6],
        [9]])]