In [1]:
# Import related packages

import numpy as np
import pandas as pd

In [2]:
# Related data

A1 = pd.DataFrame([[12, np.nan, 23, 25 ],
                   [18, None, 52, 34 ],
                   [np.nan, 14, 39, None],
                   [37, 76, 19, 10 ],
                   [47, 66, 29, 1 ]])

C1_index = [('California', 2000), ('California', 2010),
            ('New York', 2000), ('New York', 2010),
            ('Texas', 2000), ('Texas', 2010)]

populations = [33871648, 37253956, 18976457, 19378102, 20851820, 25145561]

C1 = pd.Series(populations, index=C1_index)

Data = np.round(np.random.randn(4, 6), 1)
Data[:, ::2] *= 10
Data += 37

H1=pd.DataFrame([['A1','B1','C1'],['A2','B2','C2']], index=['1','2'], columns=['A','B','C'])
H2=pd.DataFrame([['B3','C3','D3'],['B4','C4','D4']], index=['1','2'], columns=['B','C','D'])

# Q1: Detecting and droping null values

- a. print A1
- b. detecting null values in A1
- c. drop the rows which contain null in A1
- d. drop the columns which contain null in A1
- e. Keep minimum 4 non-NA entries column-wise

In [3]:
A1 = pd.DataFrame([[12, np.nan, 23, 25 ],
                   [18, None, 52, 34 ],
                   [np.nan, 14, 39, None],
                   [37, 76, 19, 10 ],
                   [47, 66, 29, 1 ]],
                 columns=list('ABCD'))

In [4]:
# a. 
print(A1)

      A     B   C     D
0  12.0   NaN  23  25.0
1  18.0   NaN  52  34.0
2   NaN  14.0  39   NaN
3  37.0  76.0  19  10.0
4  47.0  66.0  29   1.0


In [5]:
# b.detecting null values in A1

A1.isnull()

A      B      C      D
0  False   True  False  False
1  False   True  False  False
2   True  False  False   True
3  False  False  False  False
4  False  False  False  False

In [6]:
# c. drop the rows which contain null in A1

A1.dropna()

A     B   C     D
3  37.0  76.0  19  10.0
4  47.0  66.0  29   1.0

In [7]:
# d. drop the columns which contain null in A1

A1.dropna(axis=1)

C
0  23
1  52
2  39
3  19
4  29

In [8]:
# e. Keep minimum 4 non-NA entries column-wise

A1.dropna(axis=1, thresh=4)

A   C     D
0  12.0  23  25.0
1  18.0  52  34.0
2   NaN  39   NaN
3  37.0  19  10.0
4  47.0  29   1.0

# Q2: Filling null values

- a. print A1
- b. Replace all NaN elements in column 'A', 'B', 'C', and 'D', with 0, 1, 2, and 3 respectively. hint (use value parameter)
- c. Only replace the first NaN element. by default it is column-wise. (hint: use value and limit parameters)
- d. forward-fill the previous value by axis 1

In [9]:
# a. print A1

print(A1)

      A     B   C     D
0  12.0   NaN  23  25.0
1  18.0   NaN  52  34.0
2   NaN  14.0  39   NaN
3  37.0  76.0  19  10.0
4  47.0  66.0  29   1.0


In [10]:
# b. Replace all NaN elements in column 'A', 'B', 'C', and 'D', with 0, 1, 2, and 3 respectively.
# hint (use value parameter)

fill = {'A':0, 'B':1, 'C':2, 'D':3}
A1.fillna(value=fill)

A     B   C     D
0  12.0   1.0  23  25.0
1  18.0   1.0  52  34.0
2   0.0  14.0  39   3.0
3  37.0  76.0  19  10.0
4  47.0  66.0  29   1.0

In [11]:
# c. Only replace the first NaN element. by default it is column-wise. (hint: use value and limit parameters)

A1.fillna(value=fill, limit=1)

A     B   C     D
0  12.0   1.0  23  25.0
1  18.0   NaN  52  34.0
2   0.0  14.0  39   3.0
3  37.0  76.0  19  10.0
4  47.0  66.0  29   1.0

In [12]:
# d. forward-fill the previous value by axis 1

A1.fillna(method='ffill', axis=1)

A     B     C     D
0  12.0  12.0  23.0  25.0
1  18.0  18.0  52.0  34.0
2   NaN  14.0  39.0  39.0
3  37.0  76.0  19.0  10.0
4  47.0  66.0  29.0   1.0

# Q3: MultiIndex as extra dimension

- a. print C1
- b. print C1_index
- c. convert C1_index as Pandas MultiIndex type
- d. re-index the C1 with C1_index, then name as C1d
- e. use unstack way to convert C1d, then name as C1e
- f. use stack way to convert C1e, then name as C1f

In [13]:
# Run before the start of answering question 3

C1_index = [('California', 2000), ('California', 2010),
            ('New York', 2000), ('New York', 2010),
            ('Texas', 2000), ('Texas', 2010)]


populations = [33871648, 37253956, 18976457, 19378102, 20851820, 25145561]

In [14]:
# a. print C1
# That is a Series multi-indexing

C1 = pd.Series(populations, index=C1_index)
print(C1)

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64


In [15]:
# b. print C1_index
print(C1_index)

[('California', 2000), ('California', 2010), ('New York', 2000), ('New York', 2010), ('Texas', 2000), ('Texas', 2010)]


In [23]:
# c. convert C1_index as Pandas MultiIndex type
C1_index = pd.MultiIndex.from_tuples(C1_index)
print(C1)

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64


In [21]:
# d. re-index the C1 with C1_index, then name as C1d

C1d = C1.reindex(C1_index)
C1d

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [25]:
# e. use unstack way to convert C1d, then name as C1e
C1e = C1d.unstack()
print(C1e)

                2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561


In [26]:
# f. use stack way to convert C1e, then name as C1f
C1f = C1e.stack()
print(C1f)

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64


# Q4: MultiIndex for columns

- a. create "row_index" by MultiIndex.from_product which contain
        levels=[[2013, 2014], [1, 2]],
        names=['year', 'visit']

- b. create "column_index" by MultiIndex.from_product which contain
        levels=[['Bob', 'Guido', 'Sue'], ['HR', 'Temp']],
        names=['patient', 'measurement']

- c. combine "row_index", "column_index" and Data by pd.DataFrame as D2

In [27]:
# a. 

row_index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]], 
                                        names=['year', 'visit'])
row_index

MultiIndex([(2013, 1),
            (2013, 2),
            (2014, 1),
            (2014, 2)],
           names=['year', 'visit'])

In [30]:
# b.

column_index = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']],
                                           names=['patient', 'measurement'])
column_index

MultiIndex([(  'Bob',   'HR'),
            (  'Bob', 'Temp'),
            ('Guido',   'HR'),
            ('Guido', 'Temp'),
            (  'Sue',   'HR'),
            (  'Sue', 'Temp')],
           names=['patient', 'measurement'])

In [33]:
# Run before answering Question 4c.
print(Data)

[[28.  37.3 33.  37.5 37.  38.5]
 [41.  36.4 35.  34.9 30.  37.1]
 [46.  37.5 50.  36.7 44.  36.7]
 [46.  37.6 58.  38.2 31.  36.4]]


In [35]:
# c. combine "row_index", "column_index" and D1 by pd.DataFrame as D2

D2 = pd.DataFrame(Data, index=row_index, columns=column_index)
print(D2)

patient       Bob       Guido         Sue      
measurement    HR  Temp    HR  Temp    HR  Temp
year visit                                     
2013 1       28.0  37.3  33.0  37.5  37.0  38.5
     2       41.0  36.4  35.0  34.9  30.0  37.1
2014 1       46.0  37.5  50.0  36.7  44.0  36.7
     2       46.0  37.6  58.0  38.2  31.0  36.4


# Q5: Multiple index DataFrames

- a. print D2
- b. select 'Sue' column from D2
- c. select 'HR' column in 'Sue' column from D2
- d. select '2014' row and 'Guido' column from D2. (using iloc)
- e. select '2013' row and 'HR' column in 'Guido' column from D2. (using loc)
- f. select 'visit'=2 row and 'Temp' column from D2. (recall loc and idx)

In [36]:
# a.

print(D2)

patient       Bob       Guido         Sue      
measurement    HR  Temp    HR  Temp    HR  Temp
year visit                                     
2013 1       28.0  37.3  33.0  37.5  37.0  38.5
     2       41.0  36.4  35.0  34.9  30.0  37.1
2014 1       46.0  37.5  50.0  36.7  44.0  36.7
     2       46.0  37.6  58.0  38.2  31.0  36.4


In [39]:
# b. select 'Sue' column from D2

D2['Sue']

measurement    HR  Temp
year visit             
2013 1       37.0  38.5
     2       30.0  37.1
2014 1       44.0  36.7
     2       31.0  36.4

In [40]:
# c. select 'HR' column in 'Sue' column from D2
D2['Sue', 'HR']

year  visit
2013  1        37.0
      2        30.0
2014  1        44.0
      2        31.0
Name: (Sue, HR), dtype: float64

In [44]:
# d. select '2014' row and 'Guido' column from D2. (using iloc)
D2.iloc[2:, 2:4]

patient     Guido      
measurement    HR  Temp
year visit             
2014 1       50.0  36.7
     2       58.0  38.2

In [47]:
# e. select '2013' row and 'HR' column in 'Guido' column from D2. (using loc)
D2.loc[2013, ('Guido', 'HR')]

visit
1    33.0
2    35.0
Name: (Guido, HR), dtype: float64

In [48]:
# f. select 'visit'=2 row and 'Temp' column from D2. (recall loc and idx)
idx = pd.IndexSlice
D2.loc[idx[:, 2], idx[:, 'Temp']]

patient       Bob Guido   Sue
measurement  Temp  Temp  Temp
year visit                   
2013 2       36.4  34.9  37.1
2014 2       37.6  38.2  36.4

# Q6: Data Aggregations on Multi-Indices

- a. print D2
- b. take the sum among levels on the visit row
- c. take the sum among levels on the patient column

In [49]:
# a.

print(D2)

patient       Bob       Guido         Sue      
measurement    HR  Temp    HR  Temp    HR  Temp
year visit                                     
2013 1       28.0  37.3  33.0  37.5  37.0  38.5
     2       41.0  36.4  35.0  34.9  30.0  37.1
2014 1       46.0  37.5  50.0  36.7  44.0  36.7
     2       46.0  37.6  58.0  38.2  31.0  36.4


In [50]:
# b. take the sum among levels on the visit row
data_sum = D2.sum(level='visit')
data_sum

C:\Users\mabo2\AppData\Local\Temp\ipykernel_30440\3287453958.py:2: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.sum(level=1) should use df.groupby(level=1).sum().
  data_sum = D2.sum(level='visit')


patient       Bob       Guido         Sue      
measurement    HR  Temp    HR  Temp    HR  Temp
visit                                          
1            74.0  74.8  83.0  74.2  81.0  75.2
2            87.0  74.0  93.0  73.1  61.0  73.5

In [51]:
# c. take the sum among levels on the patient column

data_sum = D2.sum(level='patient', axis=1)
data_sum

C:\Users\mabo2\AppData\Local\Temp\ipykernel_30440\837681492.py:3: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.sum(level=1) should use df.groupby(level=1).sum().
  data_sum = D2.sum(level='patient', axis=1)


patient      Bob  Guido   Sue
year visit                   
2013 1      65.3   70.5  75.5
     2      77.4   69.9  67.1
2014 1      83.5   86.7  80.7
     2      83.6   96.2  67.4

# Q7: Simple Concatenation with pd.concat

- a. print E1
- b. print E2
- c. concat E1 and E2 by row
- d. fix the duplicate indices problem on c (hint: use ignore_index)
- e. concat E1 and E2 by column

In [52]:
E1=pd.DataFrame([['A1','B1','C1'],['A2','B2','C2']], index=['1','2'], columns=['A','B','C'])

E2=pd.DataFrame([['B3','C3','D3'],['B4','C4','D4']], index=['1','2'], columns=['B','C','D'])

In [53]:
# a. 
print(E1)

    A   B   C
1  A1  B1  C1
2  A2  B2  C2


In [54]:
# b.

print(E2)

    B   C   D
1  B3  C3  D3
2  B4  C4  D4


In [55]:
# c.

pd.concat([E1, E2])

A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
1  NaN  B3  C3   D3
2  NaN  B4  C4   D4

In [56]:
# d.
pd.concat([E1, E2], ignore_index=True)

A   B   C    D
0   A1  B1  C1  NaN
1   A2  B2  C2  NaN
2  NaN  B3  C3   D3
3  NaN  B4  C4   D4

In [57]:
# concat H1 and H2 by column

pd.concat([E1, E2], axis=1)

A   B   C   B   C   D
1  A1  B1  C1  B3  C3  D3
2  A2  B2  C2  B4  C4  D4