In [1]:
# import relate packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets

import warnings
warnings.filterwarnings('ignore')

In [2]:
# run before starting to answer
Boston = datasets.load_boston()
boston = np.concatenate((Boston['data'],Boston['target'].reshape(506,1)),axis=1)
boston = pd.DataFrame(boston, columns= ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 
                                     'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV'])

- Ques-1: Overview of the data
    - a. print the number of samples in the boston data
    - b. print the number of features in the boston data
    - c. view first 5 rows of the boston data

In [3]:
# 1-a
len(boston)

506

In [4]:
# 1-b
len(boston.columns)

14

In [5]:
# 1-c
boston.head(5)

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

- Ques 2: Features matrix and target array
    - a. separate the boston data into X and y (hint y= MEDV)
    - b. the shape of X
    - c. the shape of y
    - d. print X and y

In [35]:
# 2-a
X = boston.drop('MEDV', axis=1)
y = boston['MEDV']

In [37]:
# 2-b
X.shape

(506, 13)

In [8]:
# 2-c
y.shape

(506,)

In [9]:
# 2-d
print(X)
print(y)

        CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       1

- Ques 3: Linear regression
    - a. import the linear regression class
    - b. fit the boston data with a linear regression using hyperparameter intercept term
    - c. print the coefficient of features
    - d. print the coefficient of intercept term

In [38]:
# 3-a
from sklearn.linear_model import LinearRegression

In [39]:
# 3-b
model = LinearRegression(fit_intercept=True)
model.fit(X, y)

LinearRegression()

In [40]:
# 3-c
model.coef_

array([-1.08011358e-01,  4.64204584e-02,  2.05586264e-02,  2.68673382e+00,
       -1.77666112e+01,  3.80986521e+00,  6.92224640e-04, -1.47556685e+00,
        3.06049479e-01, -1.23345939e-02, -9.52747232e-01,  9.31168327e-03,
       -5.24758378e-01])

In [41]:
# 3-d
model.intercept_

36.459488385089855

- Ques 4: Predict and measure the model performance using mean squared error 
- a. import the mean_squared_error class from metrics module of sklearn library
- b. predict MEDV for the boston data
- c. evaluate the mean squared error between predict MEDV and real MEDV

In [42]:
# 4-a
from sklearn.metrics import mean_squared_error

In [43]:
# 4-b
y_pred = model.predict(X)

In [44]:
# 4-c
y_true = boston['MEDV']
mean_squared_error(y_true, y_pred)

21.894831181729202

- Ques 5: Model validation using holdout dataset
 - a. import the train_test_split class
 - b. split the boston data into X_train, X_test, y_train ,and y_test with 50% in each set (Note: set random_state=1)
 - c. fit the train data with a linear regression
 - d. predict MEDV for the test data
 - e. evaluate the mean squared error between predict MEDV and real MEDV of test data

In [45]:
# 5-a
from sklearn.model_selection import train_test_split

In [46]:
# 5-b
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.5, random_state=1)

In [47]:
# 5-c
model.fit(Xtrain, ytrain)

LinearRegression()

In [48]:
# 5-d
y_pred = model.predict(Xtest)

In [49]:
# 5-e
mean_squared_error(ytest, y_pred)

22.8392870386404

- Ques 6: Model validation using cross-validation
    - a. import the cross_val_score class from model_selection module of sklearn library
    - b. use Scikit-Learn's cross_val_score to split the boston data into five
fold and evaluate the model fit by 'neg_mean_squared_error'
    - c. use Scikit-Learn's cross_val_score to split the boston data into five
fold and evaluate the model fit by 'neg_mean_absolute_error'

In [50]:
# 6-a
from sklearn.model_selection import cross_val_score

In [52]:
# 6-b and c
scores_squared = cross_val_score(model, X, y, scoring='neg_mean_squared_error', cv=5)
scores_abs = cross_val_score(model, X, y, scoring='neg_mean_absolute_error', cv=5)

print(scores_squared, scores_abs)

[-12.46030057 -26.04862111 -33.07413798 -80.76237112 -33.31360656] [-2.62190565 -3.90725478 -4.386606   -5.57073637 -4.76333993]


- Ques 7 : Classification problem
    - a. load the iris data from sklearn.datasets
    - b. set data as iris_X, target as iris_y
    - c. instantiate iris_model using GaussianNB model from naive_bayes library of sklearn 
    and fit the model to the data
    - d. predict the iris_X data and evaluate the model fit using accuracy_score function
    - e. split the iris data into five fold and evaluate the model fit

In [26]:
from sklearn.metrics import accuracy_score

In [27]:
# 7-a
from sklearn.datasets import load_iris
iris = load_iris()

In [28]:
# 7-b
iris_X = iris.data
iris_y = iris.target

In [29]:
# 7-c
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(iris_X, iris_y)

GaussianNB()

In [30]:
# 7-d
y_model = model.predict(iris_X)
accuracy_score(iris_y, y_model)

0.96

In [31]:
# 7-e
cross_val_score(model, iris_X, iris_y, cv=5)

array([0.93333333, 0.96666667, 0.93333333, 0.93333333, 1.        ])